<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{899b5391-5363-4fd8-835e-d1662fef51af}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbGenerateTimeData_TEST	:	GenerateTimeData_TEST;
	fbHelperFunctions_TEST: ConvertAnyToString_TEST;
	fbDynamicStringBuffer_TEST: DynamicStringBuffer_TEST;
	testWrapper	:	TestWrapper_NET();
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();

testWrapper();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>