<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TESTS" Id="{379526ca-9719-4af5-b69e-537f4c5508c9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TESTS
VAR
  DateTime_TEST : DateTime_TEST;
  HelperFunctions_TEST : ConvertAnyToString_TEST;
  DynamicStringBuffer_TEST : DynamicStringBuffer_TEST;
  TestWrapper : TestWrapper_NET();
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();

TestWrapper();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>