<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{899b5391-5363-4fd8-835e-d1662fef51af}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	DateTime_TEST : DateTime_TEST;
	HelperFunctions_TEST : ConvertAnyToString_TEST;
	DynamicStringBuffer_TEST : DynamicStringBuffer_TEST;
	TestWrapper : TestWrapper_NET();
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();

TestWrapper();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>