<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TESTS" Id="{9fa91a1a-0294-47df-b5f4-55b91ebaa63a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TESTS
VAR
	DateTime_TEST : DateTime_TEST;
	HelperFunctions_TEST : ConvertAnyToString_TEST;
	DynamicStringBuffer_TEST : DynamicStringBuffer_TEST;
	TestWrapper : TestWrapper_NET();
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();

TestWrapper();]]></ST>
    </Implementation>
    <LineIds Name="TESTS">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>