name: Build/Test
on:
  push:
    branches:
      - main
    paths:
      - 'TcLog/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  Build:
    name: Build/Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: Zeugwerk/zkbuild-action@1.0.0
        with:
          username: ${{ secrets.ACTIONS_ZGWK_USERNAME }}
          password: ${{ secrets.ACTIONS_ZGWK_PASSWORD }}
      - name: Publish Unittest
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: archive/tests/**/TcUnit_xUnit_results.xml
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: TcLog
          path: |
            **/*.compiled-library    
